from __future__ import annotations

# HTTP status mapping per docs/architecture/11-error-handling-strategy.md
ERROR_CODE_TO_HTTP: dict[str, int] = {
    "VALIDATION_ERROR": 400,
    "PROPERTY_NOT_FOUND": 404,
    "PROPERTY_DELETED": 410,
    "CONCURRENCY_CONFLICT": 409,
    "DUPLICATE_PROPERTY": 409,
    "DUPLICATE_LISTING": 409,
    "IDEMPOTENCY_CONFLICT": 409,
    "INVALID_STATUS_TRANSITION": 422,
    "IMMUTABLE_FIELD": 422,
    "LOCATION_REQUIRED": 422,
    "TYPE_CATEGORY_MISMATCH": 422,
    "AREA_INVALID": 422,
    "PRICE_REQUIRED_FOR_LISTING": 422,
    "IMAGE_REQUIRED_FOR_LISTING": 422,
    "OWNERSHIP_EXCEEDS_100": 422,
    "DUPLICATE_OWNER": 422,
    "INVALID_FIELDS_FOR_TYPE": 422,
    "INVALID_CONSTRUCTION_YEAR": 422,
    "COORDINATES_REQUIRED": 422,
    "INVALID_LISTING_URL": 422,
    "UNSUPPORTED_PROVIDER": 422,
    "BULK_LIMIT_EXCEEDED": 422,
    "TENANT_MISMATCH": 403,
    "FORBIDDEN": 403,
    "UNAUTHORIZED": 401,
    "RATE_LIMIT_EXCEEDED": 429,
    "IMPORT_JOB_FAILED": 500,
    "GEOCODING_FAILED": 502,
    "STORAGE_ERROR": 502,
    "INTERNAL_ERROR": 500,
    "SERVICE_UNAVAILABLE": 503,
}

# Domain validation errors surfaced from domain layer use 422 unless listed above.
_DOMAIN_VALIDATION_CODES = frozenset({
    "LOCATION_REQUIRED",
    "TYPE_CATEGORY_MISMATCH",
    "INVALID_FIELDS_FOR_TYPE",
    "CURRENCY_REQUIRED",
    "MULTIPLE_PRIMARY_IMAGES",
    "AREA_INVALID",
    "FLOOR_INVALID",
    "INVALID_CONSTRUCTION_YEAR",
    "PRICE_REQUIRED_FOR_LISTING",
    "IMAGE_REQUIRED_FOR_LISTING",
    "COORDINATES_REQUIRED",
    "OWNERSHIP_EXCEEDS_100",
    "DUPLICATE_OWNER",
    "INVALID_OWNERSHIP_DATES",
    "INVALID_LISTING_URL",
    "UNSUPPORTED_PROVIDER",
})

for _code in _DOMAIN_VALIDATION_CODES:
    ERROR_CODE_TO_HTTP.setdefault(_code, 422)


def http_status_for_code(code: str) -> int:
    return ERROR_CODE_TO_HTTP.get(code, 500)


def is_client_error(status_code: int) -> bool:
    return 400 <= status_code < 500
